// ZomboidCraft - the "Caderno de Sobrevivência" and the crumpled recipe notes (KubeJS 6 / LootJS 2.x / Patchouli, Forge 1.20.1).
// EMI is creative-only (client_scripts/zc_emi_gamemode.js) and the vanilla recipe book is gone
// (startup_scripts/zc_no_recipe_book.js), so in survival recipes are found on paper:
//   kubejs:survival_journal - every survivor starts with it: a worn Patchouli book (zc_hair:caderno) whose pages
//                             unlock as recipes are stored in it (invisible advancements zc_recipes:learned/*)
//   kubejs:recipe_note      - loot; the first look fixes ONE random essential recipe on it (prefers unknown ones).
//                             Using it stores the recipe in the notebook and the note is used up. A note whose
//                             recipe is already in your notebook stays in your hand: trade it or copy it.
// Notes can be copied: note + paper + black dye (or ink sac / charcoal) -> 2 notes.
// The list of recipes (and the book itself) is generated by docs/tools/gen_recipe_book.js -> zc_recipe_notes_list.js.
// Rhino: no `const` inside functions that run more than once ("redeclaration of var"), hence `let`.
// Everything is wrapped in a function: KubeJS shares one global scope between script files.
(function () {
  const BOOK = 'zc_hair:caderno'   // book.json ships in zc_hair.jar (Patchouli only reads books from mod jars)
  const JOURNAL = 'kubejs:survival_journal'
  const NOTE = 'kubejs:recipe_note'
  const GIVEN = 'zc_journal_given'
  const Patchouli = Java.loadClass('vazkii.patchouli.api.PatchouliAPI')
  const RL = Java.loadClass('net.minecraft.resources.ResourceLocation')

  // ---------------------------------------------------------------- which entries really work (rebuilt after /reload)
  let checkedFor = null, usable = []
  function entries(server) {
    let manager = server.recipeManager
    if (checkedFor === manager) return usable
    let missing = []
    usable = ZC_RECIPE_NOTES.filter(n => {
      let ok = Item.exists(n[0]) && n[3].every(id => manager.byKey(new RL(id)).isPresent())
      if (!ok) missing.push(n[0])
      return ok
    })
    checkedFor = manager
    console.info(`[ZC] recipe notes: ${usable.length}/${ZC_RECIPE_NOTES.length} recipes usable` + (missing.length ? `, missing: ${missing.join(' ')}` : ''))
    return usable
  }

  // ---------------------------------------------------------------- knowledge = the invisible advancements
  function knows(player, note) {
    let adv = player.server.advancements.getAdvancement(new RL(note[2]))
    return adv != null && player.advancements.getOrStartProgress(adv).isDone()
  }
  function pick(player) {
    let all = entries(player.server)
    let fresh = all.filter(e => !knows(player, e))
    let pool = fresh.length > 0 ? fresh : all
    return pool.length > 0 ? pool[Math.floor(Math.random() * pool.length)] : null
  }
  function nameOf(note) { return Text.translate(String(Item.of(note[0]).item.getDescriptionId())) }
  function nameJson(note) {
    return JSON.stringify({ translate: 'zc.recipes.note_name', with: [{ translate: String(Item.of(note[0]).item.getDescriptionId()) }], italic: false })
  }

  // the client needs the advancement packet before Patchouli shows the page: open a few ticks later
  function openAt(player, entry) {
    player.server.scheduleInTicks(10, () => {
      try {
        if (entry) Patchouli.get().openBookEntry(player, new RL(BOOK), new RL(entry), 0)
        else Patchouli.get().openBookGUI(player, new RL(BOOK))
      } catch (e) { console.error('[ZC] recipe notes: could not open the notebook: ' + e) }
    })
  }

  // ---------------------------------------------------------------- using a note
  ItemEvents.rightClicked(NOTE, event => {
    let player = event.player
    let stack = event.item
    let id = stack.nbt && stack.nbt.contains('zc_recipes') ? String(stack.nbt.getString('zc_recipes')) : ''
    let note = id ? entries(player.server).find(n => n[0] === id) : null
    if (!note) note = pick(player)   // an unread note: decide what is written on it
    if (!note) {
      player.setStatusMessage(Text.translate('zc.recipes.empty').gray())
    } else if (knows(player, note)) {
      // already in the notebook: keep the note (now readable) to trade or copy
      if (!id) stack.nbt = { zc_recipes: note[0], display: { Name: nameJson(note) } }
      player.setStatusMessage(Text.translate('zc.recipes.already', nameOf(note)).gray())
    } else {
      player.unlockAdvancement(note[2])
      stack.shrink(1)
      let all = entries(player.server)
      let count = all.filter(n => n === note || knows(player, n)).length
      player.setStatusMessage(Text.translate('zc.recipes.learned', nameOf(note), String(count), String(all.length)).gold())
      player.server.runCommandSilent(`playsound minecraft:item.book.page_turn player ${player.username}`)
      openAt(player, note[1])
    }
    // KubeJS 6: cancel() ends the handler on the spot, so it must be the last call
    event.cancel()
  })

  ItemEvents.rightClicked(JOURNAL, event => {
    openAt(event.player, null)
    event.cancel()
  })

  // Every survivor starts with the notebook (players from before this update get it on their next login).
  PlayerEvents.loggedIn(event => {
    let player = event.player
    if (player.persistentData.getBoolean(GIVEN)) return
    player.persistentData.putBoolean(GIVEN, true)
    player.give(JOURNAL)
  })

  // ---------------------------------------------------------------- copying notes (trading recipes)
  ServerEvents.recipes(event => {
    event.shapeless('2x ' + NOTE, [NOTE, 'minecraft:paper', Ingredient.of(['#forge:dyes/black', 'minecraft:ink_sac', 'minecraft:charcoal'])])
      .modifyResult((grid, result) => {
        let note = grid.find(Item.of(NOTE))
        // an unread note copies into one unread note: no free random recipes
        if (!note || !note.nbt || !note.nbt.contains('zc_recipes')) return Item.of(NOTE)
        return result.withNBT(note.nbt)
      })
      .id('zomboidcraft:copy_recipe_note')
  })

  // ---------------------------------------------------------------- where to find them
  LootJS.modifiers(event => {
    // homes, shops, schools, offices... anything with paper in it: better odds (sometimes two notes)
    let PAPERY = /.*(house|home|casa|residen|apartment|office|escritorio|school|escola|library|biblioteca|shop|store|loja|mercado|hospital|clinic|police|policia|military|militar|bunker|story).*/
    event.addLootTableModifier(PAPERY)
      .randomChance(0.22)
      .addLoot(NOTE)
    event.addLootTableModifier(PAPERY)
      .randomChance(0.06)
      .addLoot(NOTE)
    // any other chest
    event.addLootTypeModifier(LootType.CHEST)
      .randomChance(0.07)
      .addLoot(NOTE)
  })
})()
